//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025. 04. 08. 20:42:06
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace cnKepzesek
{
    public partial class Oktato {

        public Oktato()
        {
            this.Kepzesek = new List<Kepzes>();
            OnCreated();
        }

        public int ID { get; set; }

        public string Nev { get; set; }

        public string Szakterulet { get; set; }

        public virtual IList<Kepzes> Kepzesek { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
