//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025. 04. 08. 20:42:06
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace cnKepzesek
{
    public partial class Kepzes {

        public Kepzes()
        {
            this.Oktatok = new List<Oktato>();
            this.Resztvevoks = new List<Resztvevo>();
            OnCreated();
        }

        public int ID { get; set; }

        public string Nev { get; set; }

        public DateTime KezdesDatuma { get; set; }

        public DateTime BefejezesDatuma { get; set; }

        public string Hely { get; set; }

        public virtual IList<Oktato> Oktatok { get; set; }

        public virtual IList<Resztvevo> Resztvevoks { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
